[project]
name = "stitch"
version = "1.4.1"
description = ""
authors = [
    { name = "Alon Schwartzblat", email = "alon.ponch@gmail.com" },
]
requires-python = ">=3.11"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
dependencies = [
    "PyYAML",
    "androguard",
    "pyaxml"
]
[project.optional-dependencies]
dev = [
    "pytest",
    "flake8",
]

[build-system]
requires = ["setuptools>=81.0.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"*" = ["bin/*"]
[tool.pytest.ini_options]
pythonpath = ["src", "tests"]
testpaths = ["tests"]
